spring:
  mail:
    host: smtp.qq.com

    username: 2869245558@qq.com
    #授权码
    password: drdueonrojwodchj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8

