person:
  name: qinjiang${random.uuid} # 随机uuid
  age: ${random.int} # 随机int
  happy: false
  birth: 2000/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog: # 引用person.hello 的值，如果不存在就用 ：后面的值，即 other，然后拼接上_旺财
    name: ${person.hello:other}_旺财
    age: 1

dog:
  name: "小黑"
  age: 11

fish:
  age: 24
  email: 2869245558@qq.com
  name: 中单


server:
  port: 8081

